name: PHPCS Tests
on:
  push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  phpcs_tests:
    name: PHPCS Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v3
        id: cache-composer
        with:
          path: vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
      - name: Composer install
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: make composer ARGS=install
      - name: PHPCS checks
        run: make phpcs